# Generated by Django 5.1.7 on 2025-04-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendrequest",
            name="status",
        ),
    ]
